# Generated by Django 5.0 on 2023-12-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('capital', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=200)),
                ('population', models.IntegerField()),
            ],
        ),
    ]
